name 'ubuntu'
version '0.9.0'

summary 'A puppet module for managing ubuntu images'
author 'Bill Hazard'
license 'MIT'
project_page 'http://github.com/bhazard/vagrant-railsdev'
source 'http://github.com/bhazard/vagrant-railsdev'
description 'Cleans up the default ubuntu image'

#dependency 'puppetlabs/stdlib', '>=3.2.0'
# not included as a dependency to avoid installing it when is not needed most times.
#dependency 'puppetlabs/apache', '>=0.9.0'
